### PR TITLE
Create GiusepeCasagrande.cs

### PR DESCRIPTION
**Pull request by GiusepeCasagrande**
Added myself

### CODE REVIEW

**Comment by jfversluis** [comment]
You didn't add yourself to the project file? So this class won't be included in the builds

**Comment by jamesmontemagno** [comment]
Needs to be added to the .csproj... maybe we should add this to the readme? If you are using VS Code then it doesn't auto do this

**Comment by GiusepeCasagrande** [comment]
Opps, sorry, I edited the file directly in the github. Let me fix that.

**Comment by GiusepeCasagrande** [comment]
Ok guys, csproject updated. Sorry for the trouble. :)

**Pull request merged**
