### PR TITLE
Added new author

### PR DESCRIPTION
**Pull request by TimLariviere**
If you are submitting a new blog please read:

By sending this pull request to add my blog I verify that I adhere to the Planet Xamarin blog guidelines:

- I have a valid blog & RSS URL
- Host NO malicious or offensive content on the blog (including photos, swearing, etc.)
- Blog is active with at least 3 Xamarin related blog posts in the last 6 months
- If the blog has mixed content (Xamarin and Personal/Non-Xamarin blogs) a filter has been applied
- If you delete your blog you will come delete your blog from Planet Xamarin
- Your blog may be removed at any time if any of these are broken.

### CODE REVIEW

**Comment by Cheesebaron** [comment]
Technically your blog does not fall within "Blog is active with at least 3 Xamarin related blog posts in the last 6 months".

Last post was in October last year. The two prior were in July. However one of them were 21, which falls out of last 6 months.

What do you say @ghuntley, @jamesmontemagno, @jfversluis ?

**Comment by jfversluis** [comment]
Hm, hm. Though one, maybe @TimLariviere can solemnly swear to do better?

**Comment by TimLariviere** [comment]
Oh, I didn't think that those posts were already that old.

Well, I do have more posts to write in the next few days.
So I will definitely keep on posting about Xamarin, hopefully at a faster rate.

**Comment by Cheesebaron** [comment]
I guess we can fit you in 😉

**Pull request merged**
