### PR TITLE
Adding Syncfusion Xamarin blogs.

### PR DESCRIPTION
**Pull request by prabakaranr**
:pencil2: **Blog Url**: https://www.syncfusion.com/blogs/

:scroll: **Feed Url**: https://www.syncfusion.com/blogs/feed

By sending this pull request to add my blog I verify that I adhere to the Planet Xamarin blog guidelines (please check each item that applies):

- [x] I have a valid blog & RSS URL, both using HTTPS :lock: with a valid certificate
- [x] I host NO malicious or offensive content on the blog (including photos, swearing, etc.)
- [x] My blog is active with at least 3 Xamarin related blog posts in the last 6 months
- [x] In addition to the previous guideline; it should be apperant that the blog is active for a longer period of time and the posts on it are not fabricated in a small amount of time to comply to the '3 posts in last 6 months' guideline.
- [x] I have applied a filter (Optional: if blog is only about Xamarin or you use `xamarin` in the title or categories in your blog posts)
- [x] I have added my Author class to the csproj file
- [x] I have implemented `IAmACommunityMember` or one of the other derivatives
- [x] I understand, if I delete my blog, I will be deleted from Planet Xamarin
- [x] I understand, my blog may be removed at any time if any of these guidelines are broken.
- [ ] The submitted blog is not owned by a company which sole purpose it is to advertise a product of productline.

Only the collaborators of this repository decide whether a blog is eligible or not. They will determine if the rules are followed and if the quality of the content is high enough. 

Opening another PR, after the first one is closed in a small period of time will not be reevaluated. If a PR is closed, the issues with your blog are too significant to be fixed within a matter of hours.

### CODE REVIEW

**Comment by Cheesebaron** [comment]
> The submitted blog is not owned by a company which sole purpose it is to advertise a product of productline

This one is unticked. This is a community blog aggregator. Not sure if this blog is fit for PlanetXamarin. @planetxamarin/owners what do you think?

**Comment by jfversluis** [comment]
Hm a quick scan at the provided link I see that all content is actually tailored toward their own controls. Not sure if this would be a great fit.

**Comment by jamesmontemagno** [comment]
So, I actually would encourage different component vendors to put their blog with quality content in there. I find it all very interesting and I think is a pretty good fit based on correct filters as long as it isn't sales.

For instance: https://www.syncfusion.com/blogs/category/xamarin is better with the category.

**Comment by Cheesebaron** [comment]
That is the category that would be picked up.

We could add them and if the content becomes too sales oriented in the future, we could simply remove them. I wouldn't mind.

**Comment by jfversluis** [comment]
Sounds good to me!

**Pull request merged**
