### PR TITLE
Added new author from Poland.

### PR DESCRIPTION
**Pull request by kstepnikowski**
If you are submitting a new blog please read:

By sending this pull request to add my blog I verify that I adhere to the Planet Xamarin blog guidelines (please check each item that applies):

- [ ] I have a valid blog & RSS URL
- [ ] I host NO malicious or offensive content on the blog (including photos, swearing, etc.)
- [ ] My blog is active with at least 3 Xamarin related blog posts in the last 6 months
- [ ] I have applied a filter (Optional: if blog is only about Xamarin)
- [ ] I understand, if I delete my blog, I will be deleted from Planet Xamarin
- [ ] I understand, my blog may be removed at any time if any of these guidelines are broken.

### CODE REVIEW

**Comment by kstepnikowski** [comment]
Sorry. I've just added the file in the csproj file.

**Comment by jfversluis** [comment]
And did you push it? I don't see any additional changes.

**Comment by kstepnikowski** [comment]
Oh sorry. I'm in a work. I have blocked push command doing here. If you can add this file in the csproj file, I will be grateful.

**Comment by jfversluis** [comment]
I have further inspected your blog and I see a few more issues before we can consider adding you.
 - Add the class to the csproj file (we already knew this one ;))
 - I see your posts aren't purely Xamarin, please implement the IFilterMyPosts interface
 - You do not seem to make the 'three posts in the past 6 months' rule or just barely, so make sure you have enough content on there to be considered.

Also, if I might add a suggestion on a personal note: do not add your code as images. People cannot copy/paste anything out of it and it impacts search results leading to you.

I will close this PR for now, please work on these issues and try again later when you think you are ready!

**Pull request closed without merging**
