### PR TITLE
Add Pierce Boggan

### PR DESCRIPTION
**Pull request by pierceboggan**
Adds Pierce to the Planet Xamarin feed.

### CODE REVIEW

**Comment by pierceboggan** [comment]
Adding @jamesmontemagno for review. 👍

**Comment by jamesmontemagno** [comment]
Did you add yourself to the csproj?

**Comment by pierceboggan** [comment]
So smart James, so smart...

**Comment by Cheesebaron** [comment]
Hey @pierceboggan, could I get you to fill out the Pull Request Template, please? 😄

**Pull request closed without merging**
