### PR TITLE
Andrew Hoefling: Adjusted Feed to Include Uno Platform Posts

### PR DESCRIPTION
**Pull request by ahoefling**
I am planning to add Uno Platform posts to my blog and since it uses Xamarin Native, I wanted to update my feed here. The new feed url will share both Xamarin and Uno Platform articles

If this isn't recommended, feel free to just close this PR

### CODE REVIEW

**Comment by Cheesebaron** [comment]
Category needs to be xamarin or contain xamarin in the title. That is the default filter at least. So if you make sure that is the case @ahoefling then the posts will show up. Otherwise, you would need to implement `IFilterMyBlogPosts` and do your own logic in there.

**Comment by ahoefling** [comment]
Thanks for the explanation on how Planet Xamarin filters out blog titles and categories that contain `Xamarin`. I took the easy way out of and never implemented `IFilterMyBlogPosts` as my RSS Feed can be filtered with query strings 
```
?category=Xamarin,uno-platform
``` 
which will return both categories
```
?category=Xamarin
``` 
which will just return Xamarin articles.

All of that set aside, Uno Platform by design uses Xamarin Native and I would argue it could be included in the RSS feeds here since it is talking about cross-platform development with Xamarin Native as the base implementation, using a different cross-platform code sharing strategy. 

It may be as simple as adding a Xamarin `category` to each of my Uno Platform blog posts so the Planet Xamarin filter doesn't exclude it.

If we want to keep this feed to Xamarin Native and Xamarin.Forms, we can close this request.

**Comment by jamesmontemagno** [comment]
Holding off on merging any new PRs currently, please hold

**Comment by Cheesebaron** [comment]
@jamesmontemagno are we still holding back or?

**Review by Cheesebaron — APPROVED** [review]

**Pull request merged**
