### PR TITLE
Add me to the flow of planetxamarin

### PR DESCRIPTION
**Pull request by JoacimWall**
:pencil2: **Blog Url**: 

:scroll: **Feed Url**: 

By sending this pull request to add my blog I verify that I adhere to the Planet Xamarin blog guidelines (please check each item that applies):

- [x] I have a valid blog & RSS URL, both using HTTPS :lock: with a valid certificate
- [x] I host NO malicious or offensive content on the blog (including photos, swearing, etc.)
- [x] My blog is active with at least 3 Xamarin related blog posts in the last 6 months
- [x] In addition to the previous guideline; it should be apperant that the blog is active for a longer period of time and the posts on it are not fabricated in a small amount of time to comply to the '3 posts in last 6 months' guideline.
- [ ] I have applied a filter (Optional: if blog is only about Xamarin or you use `xamarin` in the title or categories in your blog posts)
- [x] I have added my Author class to the csproj file
- [x] I have implemented `IAmACommunityMember` or one of the other derivatives
- [x] I understand, if I delete my blog, I will be deleted from Planet Xamarin
- [x] I understand, my blog may be removed at any time if any of these guidelines are broken.
- [x] The submitted blog is not owned by a company which sole purpose it is to advertise a product of productline.

Only the collaborators of this repository decide whether a blog is eligible or not. They will determine if the rules are followed and if the quality of the content is high enough. 

Opening another PR, after the first one is closed in a small period of time will not be reevaluated. If a PR is closed, the issues with your blog are too significant to be fixed within a matter of hours.

### CODE REVIEW

**Comment by JoacimWall** [comment]
Hi i started blogin and i have 3 more blog regarding xamarin in the pip.

**Comment by JoacimWall** [comment]
Failed UnitTest.AuthorsTest.All_Authors_Have_Secure_And_Parsable_Feed [50 s]
  Error Message:
   Feed(s) for Jim Bennett  @  is null or empty @https://www.jimbobbennett.io/rss

This is not my Feed that Failed

**Review by Cheesebaron — APPROVED** [review]

**Comment by Cheesebaron** [comment]
Don't worry about the unit tests.

I would still love you to fulfil the 3 posts in 6 months

**Comment by JoacimWall** [comment]
Hi i have not add 3 of my blogs to the site.

**Comment by JoacimWall** [comment]
Hi is there anything more that i need to do?

Thanks Joacim

**Comment by Cheesebaron** [comment]
> In addition to the previous guideline; it should be apperant that the blog is active for a longer period of time and the posts on it are not fabricated in a small amount of time to comply to the '3 posts in last 6 months' guideline.

This one is not fulfilled :)

**Comment by JoacimWall** [comment]
Hi
I can agree on that the blog has not bin active for so long but I don’t think the posts has bin fabricated in small amount of time. It’s took many hours to write them.

 Could you give some hint what’s small amount of time is because if post new articles I would be nice to be able to be a part of planetxamarin so users can find the articles. 



Thanks Joacim



Skickat från min iPhone

**Pull request merged**
