### PR TITLE
Update DanielMonetelli.cs

### PR DESCRIPTION
**Pull request by monetelli**
:pencil2: **youtube channel Url**: https://www.youtube.com/c/danielmonetelli

:scroll: **Feed Url**: https://www.youtube.com/feeds/videos.xml?channel_id=UCTAlbAORoFvAHj7jA4DLSFQ

By sending this pull request to add my blog I verify that I adhere to the Planet Xamarin blog guidelines (please check each item that applies):

- [x] I have a valid blog & RSS URL, both using HTTPS :lock: with a valid certificate
- [x] I host NO malicious or offensive content on the blog (including photos, swearing, etc.)
- [x] My blog is active with at least 3 Xamarin related blog posts in the last 6 months
- [x] In addition to the previous guideline; it should be apperant that the blog is active for a longer period of time and the posts on it are not fabricated in a small amount of time to comply to the '3 posts in last 6 months' guideline.
- [x] I have applied a filter (Optional: if blog is only about Xamarin or you use `xamarin` in the title or categories in your blog posts)
- [x] I have added my Author class to the csproj file
- [x] I have implemented `IAmAYoutuber` or one of the other derivatives
- [x] I understand, if I delete my blog, I will be deleted from Planet Xamarin
- [x] I understand, my blog may be removed at any time if any of these guidelines are broken.
- [x] The submitted blog is not owned by a company which sole purpose it is to advertise a product of productline.

Only the collaborators of this repository decide whether a blog is eligible or not. They will determine if the rules are followed and if the quality of the content is high enough. 

Opening another PR, after the first one is closed in a small period of time will not be reevaluated. If a PR is closed, the issues with your blog are too significant to be fixed within a matter of hours.

### CODE REVIEW

**Comment by monetelli** [comment]
Hello @jfversluis , two days ago I made a publication but when I enter the publications preview my publication is not in my name.

**Comment by jfversluis** [comment]
Can you tell me which one you’re talking about please?

**Comment by monetelli** [comment]
> ¿Puedes decirme de cuál estás hablando por favor?

On the page https://www.planetxamarin.com/preview the publication "Xamarin.Forms Update - Los enamorados CSS y BindableLayout" appears, another author appears, other publications of mine also have that same author.

**Comment by monetelli** [comment]
@jfversluis  on the page https://www.planetxamarin.com/preview the publication "Xamarin.Forms Update - Los enamorados CSS y BindableLayout" appears, another author appears, other publications of mine also have that same author.

**Comment by jfversluis** [comment]
It seems that video is scheduled for February 11th. It will show up after that

**Comment by monetelli** [comment]
@jfversluis other videos already published showed that the author was Jesús Ángulo, here is a screenshot of the mentioned publication https://i.pinimg.com/originals/a4/52/3b/a4523b09682dfb3d935e6395503fb3d8.png

**Comment by jfversluis** [comment]
Ah, I see what the problem is now. Could you please open an issue for this? We will look into it whenever we have time.

**Comment by jfversluis** [comment]
Also FYI, I can't view it right now. As I said, it is configured to be published in two days.

image

**Comment by monetelli** [comment]
@jfversluis it will be best to wait after this date, because I am collaborating with an initiative called "Xamarin's Month", and that day I have to release my video tutorial.

**Pull request merged**
