### PR TITLE
Remove @jmillerdev due to expired certificate

### PR DESCRIPTION
**Pull request by Cheesebaron**
@jmillerdev has a expired SSL cert failing our integration tests

### CODE REVIEW

**Comment by jfversluis** [comment]
Hm, build fails due to @HoussemDellai's feed being empty? Although it is not, I don't see any Xamarin stuff in there. Does it mark it as "empty" then?

**Comment by Cheesebaron** [comment]
@jfversluis will look into that later today. His feed is a youtube rss feed, so they might do something special or need a special filter.

**Comment by Cheesebaron** [comment]
@therealjohn I let CloudFlare take care of all my certificate woes

**Comment by jfversluis** [comment]
Still not valid, sorry @therealjohn. Please undo this when you get around to it!

**Comment by jfversluis** [comment]
It seems you can add @Geertvdc to this list with an invalid cert... Houssem is #521 I guess

**Pull request merged**
