### PR TITLE
Update Firehose.Web.csproj

### PR DESCRIPTION
**Pull request by officialdoniald**

### CODE REVIEW

**Comment by officialdoniald** [comment]
Hi,

Is this request enought or I have to pull the BenceLenart.cs and the csprojfile together?

**Comment by nickrandolph** [comment]
Please move this commit to your previous PR so that they can be approved together

**Comment by officialdoniald** [comment]
Sorry, but I get 403 when I create a PR in VS. How can I do it in GitHub?

**Comment by nickrandolph** [comment]
Closing as replaced by https://github.com/planetxamarin/planetxamarin/pull/597

**Pull request closed without merging**
