### PR TITLE
Adding Udara Alwis as an Author

### PR DESCRIPTION
**Pull request by UdaraAlwis**
:pencil2: **Blog Url**: https://theconfuzedsourcecode.wordpress.com/

:scroll: **Feed Url**: https://theconfuzedsourcecode.wordpress.com/feed/

By sending this pull request to add my blog I verify that I adhere to the Planet Xamarin blog guidelines (please check each item that applies):

- [x] I have a valid blog & RSS URL, both using HTTPS :lock: with a valid certificate
- [x] I host NO malicious or offensive content on the blog (including photos, swearing, etc.)
- [x] My blog is active with at least 3 Xamarin related blog posts in the last 6 months
- [x] In addition to the previous guideline; it should be apperant that the blog is active for a longer period of time and the posts on it are not fabricated in a small amount of time to comply to the '3 posts in last 6 months' guideline.
- [x] I have applied a filter (Optional: if blog is only about Xamarin or you use `xamarin` in the title or categories in your blog posts)
- [x] I have added my Author class to the csproj file
- [x] I have implemented `IAmACommunityMember` or one of the other derivatives
- [x] I understand, if I delete my blog, I will be deleted from Planet Xamarin
- [x] I understand, my blog may be removed at any time if any of these guidelines are broken.
- [x] The submitted blog is not owned by a company which sole purpose it is to advertise a product of productline.

Only the collaborators of this repository decide whether a blog is eligible or not. They will determine if the rules are followed and if the quality of the content is high enough. 

Opening another PR, after the first one is closed in a small period of time will not be reevaluated. If a PR is closed, the issues with your blog are too significant to be fixed within a matter of hours.

### CODE REVIEW

**Comment by jfversluis** [comment]
Site looks good, changes look good although the filter isn’t really necessary I think. We have a default filter like this implemented. 

Test is failing but not on this change. 

Pinging @webmasterdevlin are you aware your site seems to be down?

**Comment by webmasterdevlin** [comment]
My site is up. I just checked.

**Comment by jfversluis** [comment]
Ah the feed url didn’t seem to load but that seems to be because Safari on mobile doesn’t recognize the content. 

Could it be that the feed is not showing any Xamarin content? I see the latest entry is from July 2019? Maybe that it doesn’t come up in the feed and therefore our test fails because we haven’t seen any Xamarin content for the past 6 months

**Comment by Cheesebaron** [comment]
@jfversluis no xamarin related entries for that author

**Comment by Cheesebaron** [comment]
Looks good to me. Welcome to PlanetXamarin

**Comment by UdaraAlwis** [comment]
Thanks guys :) any idea when you're planning to deploy the build?

**Comment by Cheesebaron** [comment]
@jamesmontemagno can you add a task to your todo to deploy a new version, please? 😄

**Comment by UdaraAlwis** [comment]
@Cheesebaron I see the build is broken, caused by a heavy feed in one of the existing blogs. Are you guys looking into it? We could just inform the author and disable it for now until its fixed?

**Pull request merged**
