### PR TITLE
add Sam Debruyn as community member

### PR DESCRIPTION
**Pull request by SamuelDebruyn**
No filter is applied as the feed URL already contains a tag-based filter.
I know the activity on my blog could be better, but I have a few new Xamarin blogposts planned for the coming weeks so that's why I am adding myself to the list.

### CODE REVIEW

**Comment by Cheesebaron** [comment]
Well you haven't written anything the last 8 months. I'd be inclined to put this on hold until you have some new content.

**Comment by SamuelDebruyn** [comment]
No problem, I'll make sure to write at least one new post this week and the other one next week so that you can reevaluate the PR next week :)

**Comment by Cheesebaron** [comment]
@SamuelDebruyn can you ping me when you have a new post 😄

**Comment by SamuelDebruyn** [comment]
Will do :)

**Comment by SamuelDebruyn** [comment]
@Cheesebaron Published another post at https://www.chipsncookies.com/2017/a-few-common-issues-with-.csproj-files-in-xamarin-apps/ and I'm already working on the next one :)

**Comment by SamuelDebruyn** [comment]
Thanks!

**Pull request merged**
