### PR TITLE
Adds Sebastian Seidel as author

### PR DESCRIPTION
**Pull request by CayasSoftware**
If you are submitting a new blog please read:

By sending this pull request to add my blog I verify that I adhere to the Planet Xamarin blog guidelines:

- I have a valid blog & RSS URL
- Host NO malicious or offensive content on the blog (including photos, swearing, etc.)
- Blog is active with at least 3 Xamarin related blog posts in the last 6 months
- If the blog has mixed content (Xamarin and Personal/Non-Xamarin blogs) a filter has been applied
- If you delete your blog you will come delete your blog from Planet Xamarin
- Your blog may be removed at any time if any of these are broken.

### CODE REVIEW

**Comment by Cheesebaron** [comment]
I don't see "Blog is active with at least 3 Xamarin related blog posts in the last 6 months" fulfilled.

**Comment by CayasSoftware** [comment]
I took the time today to prepare my profile. But you are right - close my PR but than allow me a question: What is more important, quantity or quality?

**Comment by Cheesebaron** [comment]
I don't think 3 posts within the last 6 months is too much to ask for. However, I do agree that a qualitative requirement would be good to have.

@owners what do you think?

**Comment by Cheesebaron** [comment]
Can you please merge master into your branch so we can add you to the feed?

**Pull request merged**
