### PR TITLE
Adds profile for Thomas Bandt

### PR DESCRIPTION
**Pull request by aspnetde**
If you are submitting a new blog please read:

By sending this pull request to add my blog I verify that I adhere to the Planet Xamarin blog guidelines:

- I have a valid blog & RSS URL
- Host NO malicious or offensive content on the blog (including photos, swearing, etc.)
- Blog is active with at least 3 Xamarin related blog posts in the last 6 months
- If the blog has mixed content (Xamarin and Personal/Non-Xamarin blogs) a filter has been applied
- If you delete your blog you will come delete your blog from Planet Xamarin
- Your blog may be removed at any time if any of these are broken.

### CODE REVIEW

**Comment by Cheesebaron** [comment]
@jfversluis you didn't check dates on last posts. None of the Xamarin ones were written in the last 6 months.

**Comment by jfversluis** [comment]
Yep, you're right. I know Thomas a little, checked his blog, read one and clicked to his Github repo seeing that it was updated not a month ago.

@aspnetde sorry buddy, you're going to have to have some more posts first!

**Comment by aspnetde** [comment]
If it's more important to you what has been written in the past than what may be written (and therefore appearing in your feed) in the future, I am happy to pass. No worries. ✌🏻

**Comment by Cheesebaron** [comment]
That is your decision to make. You are of course welcome back whenever you meet the minimal criteria that we currently have.

Ultimately I would some additional quality criteria put in place because not all of the blogs are of great quality. However, that is another discussion.

**Pull request merged**
