### PR TITLE
Switch to new feed without Blogmonster 2

### PR DESCRIPTION
**Pull request by Cheesebaron**
Supersedes https://github.com/planetxamarin/planetxamarin/pull/591

### CODE REVIEW

**Comment by Cheesebaron** [comment]
We are nearing the anniversary of this and the original PR I made. I would love for some action here.

**Comment by jamesmontemagno** [comment]
Looks like we have some failures :( let's just get those in and merge it

**Comment by Cheesebaron** [comment]
@jamesmontemagno I'll fix the issues, soon.

**Comment by Cheesebaron** [comment]
@jamesmontemagno the build is not really failing, but rather the Unit Tests failing for a bunch of author's which feeds are not returning any elements.

We haven't had proper feedback for failing Unit Tests because the old blog monster feed would fail sporadically, where the new is much more resilient. They were just _always_ failing before...

**Comment by jamesmontemagno** [comment]
Ahhhh gotcha! Are we good now? I am cool pulling in :(

**Comment by Cheesebaron** [comment]
Apart from the pipeline not finding the tests I think this should be good to go.

**Comment by jamesmontemagno** [comment]
Blarg :( sorry, now we have conflics again

**Comment by Cheesebaron** [comment]
@jamesmontemagno fixed

**Comment by Cheesebaron** [comment]
@jamesmontemagno author's feed started fail:

```
Sebastian Jensen  @tsjdev-apps  is null or empty @https://www.tsjdev-apps.de/feed/
```

If you visit their feed you get this:

Screenshot 2020-03-06 at 10 15 33

**Comment by jamesmontemagno** [comment]
So, are we go? should we push the button?

**Pull request merged**
