### PR TITLE
Added my blog

### PR DESCRIPTION
**Pull request by MarcosCobena**
If you are submitting a new blog please read:

**Please do not forget to add the cs file to the csproj file!**

By sending this pull request to add my blog I verify that I adhere to the Planet Xamarin blog guidelines (please check each item that applies):

- [x] I have a valid blog & RSS URL, both using HTTPS with a valid certificate

I haven't checked this one as the RSS URL does enforce HTTPS through Feed Burner (saw other users were doing the same) but my blog one currently lives in GitHub Pages and the DNS am using doesn't provide HTTPS nowadays. Wanted to ask you guys whether serving the feed securely was valid for now until I move to a more fancy DNS.

- [x] I host NO malicious or offensive content on the blog (including photos, swearing, etc.)
- [x] My blog is active with at least 3 Xamarin related blog posts in the last 6 months
- [x] In addition to the previous guideline; it should be apperant that the blog is active for a longer period of time and the posts on it are not fabricated in a small amount of time to comply to the '3 posts in last 6 months' guideline.
- [x] I have applied a filter (Optional: if blog is only about Xamarin)
- [x] I understand, if I delete my blog, I will be deleted from Planet Xamarin
- [x] I understand, my blog may be removed at any time if any of these guidelines are broken.
- [x] The submitted blog is not owned by a company which sole purpose it is to advertise a product of productline.

Only the collaborators of this repository decide whether a blog is eligible or not. They will determine if the rules are followed and if the quality of the content is high enough. 

Opening another PR, after the first one is closed in a small period of time will not be reevaluated. If a PR is closed, the issues with your blog are too significant to be fixed within a matter of hours.

### CODE REVIEW

**Comment by Cheesebaron** [comment]
It takes 5 minutes to swap over your DNS to a service like CloudFlare, which supports the github pages scenario.

**Comment by MarcosCobena** [comment]
Ok! Let me try the move tomorrow —had some headaches with coming from a
domain created at WordPress.com but let's try 😊

Thanks Tomasz,

–Marcos


El 29 ene. 2018 8:11 p. m., "Tomasz Cielecki" <notifications@github.com>
escribió:

It takes 5 minutes to swap over your DNS to a service like CloudFlare,
which supports the github pages scenario.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/planetxamarin/planetxamarin/pull/409#issuecomment-361353103>,
or mute the thread

**Comment by MarcosCobena** [comment]
@Cheesebaron done Tomasz, thanks for pushing me! :-)

**Comment by MarcosCobena** [comment]
I've just merged latest changes.

**Comment by MarcosCobena** [comment]
Thanks for the indentation fix, need to dig why VS for Mac does this sometimes

**Pull request merged**
