### PR TITLE
Added myself (BryanAnthonyGarcia.cs) to the list of Planet Xamarin authors

### PR DESCRIPTION
**Pull request by mindofai**
If you are submitting a new blog please read:

By sending this pull request to add my blog I verify that I adhere to the Planet Xamarin blog guidelines:

- I have a valid blog & RSS URL
- Host NO malicious or offensive content on the blog (including photos, swearing, etc.)
- Blog is active with at least 3 Xamarin related blog posts in the last 6 months
- If the blog has mixed content (Xamarin and Personal/Non-Xamarin blogs) a filter has been applied
- If you delete your blog you will come delete your blog from Planet Xamarin
- Your blog may be removed at any time if any of these are broken.

### CODE REVIEW

**Comment by mindofai** [comment]
I updated the .csproj and also added few articles (4 total).

**Comment by mindofai** [comment]
Is this alright now?

**Comment by mindofai** [comment]
Hello? Is this fine now? Sorry, I just want to know if there are changes that should be made.

**Comment by Cheesebaron** [comment]
The code itself is fine. We just need to review the content on the blog.

**Comment by mindofai** [comment]
Thanks! Actually planning to add more this week.

**Comment by mindofai** [comment]
Hi, I just want to follow this up. Thanks!

**Comment by mindofai** [comment]
Thanks! :)

**Pull request merged**
