### PR TITLE
Integration tests

### PR DESCRIPTION
**Pull request by Cheesebaron**
Adds more integration tests against Author feeds.

The tests now fetch the feeds and checks whether they contain items.

### CODE REVIEW

**Comment by Cheesebaron** [comment]
@ghuntley can you please fix your feed? 😄

**Comment by Cheesebaron** [comment]
The new test fail because of the following feeds returning empty feeds:

 Output:
        Feed(s) for Geoffrey Huntley is null or empty
        Feed(s) for Marcos Barchiki dos Santos is null or empty
        Feed(s) for MFractor  is null or empty
        Feed(s) for Evgeny Zborovsky is null or empty

@ghuntley @mhbsti @matthewrdev @yuv4ik would you guys please fix your feeds? Otherwise I am going to remove them from aggregation.

**Comment by matthewrdev** [comment]
@Cheesebaron Thanks, I'll look into fixing mine.

**Comment by mhbsti** [comment]
@Cheesebaron Thanks, I'll look into fixing mine.

**Comment by Cheesebaron** [comment]
There still seems to be an issue with @matthewrdev MFractor feeds, I will have a deeper look to see if it is a flaw in my test code. The feeds seem to not be empty.

**Pull request merged**
