### PR TITLE
Fix feeds + speed 🚀

### PR DESCRIPTION
**Pull request by Cheesebaron**
- Removed some authors where blogs were severely broken.
- ~~Made detection of broken blogs parallel. Speed up from 2 minutes 30 -> 15 seconds!~~
- Replaced the built in `RemoteSyndicationFeedSource` with a simplified version and caching feeds for an hour. Brings feed loading down from 5 minutes ⚠️ down to between 30 and 50 seconds on my local machine 🚀 
- Removed poking of feeds before loading them again. Just makes a huge overhead.

### CODE REVIEW

**Comment by Cheesebaron** [comment]
I've filed a bug with BlogMonster about it being slow: https://github.com/uglybugger/BlogMonster/issues/2

I don't have much hope of it being fixed there as it is slow by design.

**Comment by Cheesebaron** [comment]
@jamesmontemagno I'd say now-ish. Won't do more right now. 🛏 is calling. It works locally on my machine.

**Comment by Cheesebaron** [comment]
I might have introduced a slight bug here, so don't merge yet.

The cache does not work correctly, I am feeding the same feed over and over again when it is invalidated.

I don't think this BlogMonster works well for us, it just does things very poorly in terms of performance.

**Comment by Cheesebaron** [comment]
This should be good to go now. I tried with a low cache timeout and it seems to reload the feed correctly. Someone please review the code.

**Comment by jfversluis** [comment]
LGTM! This performs way better than the quickfixes I had implemented.

**Pull request merged**
