### PR TITLE
Added Venkataramana Madugula as Author.

### PR DESCRIPTION
**Pull request by VenkatsQuest**
If you are submitting a new blog please read:

By sending this pull request to add my blog I verify that I adhere to the Planet Xamarin blog guidelines (please check each item that applies):

- [x] I have a valid blog & RSS URL
- [x] I host NO malicious or offensive content on the blog (including photos, swearing, etc.)
- [x] My blog is active with at least 3 Xamarin related blog posts in the last 6 months
- [x] I have applied a filter (Optional: if blog is only about Xamarin)
- [x] I understand, if I delete my blog, I will be deleted from Planet Xamarin
- [x] I understand, my blog may be removed at any time if any of these guidelines are broken.

### CODE REVIEW

**Comment by VenkatsQuest** [comment]
Hello @jfversluis @ghuntley @jamesmontemagno 
Kindly review this change and approve it. Thanks much.

**Comment by VenkatsQuest** [comment]
Can somebody help me with the below question ?
I'm sure i'm sounding anxious with this comment.
But I'm curious here to know the turn around time for the approval of code commit and considering anyone as Author for Planet Xamarin ?

**Comment by jfversluis** [comment]
There is, indeed, no need to mention everyone and keep asking when it will be accepted. We are all doing what we can and will look into it whenever we can.

As I have been doing with your blog. I am very sorry, but the content does not really live up to the standards we have in mind. Your posts seem a bit short, and in a lot of them you just link to a full article which is written on another website, https://walkingtree.tech. Therefore I cannot add your PR right now. I would like to encourage you to write awesome, interesting articles on your own blog and try again later when you feel you have enough content.

**Comment by VenkatsQuest** [comment]
First of all apologies for keep on asking you about everywhere.

Thanks for your response I'll work on improving and providing more content.

I'm not sure whether you would've got a chance to look at https://WalkingTree.tech. There also I'm The Author itself.So rather than repeating the content, I just added a link there. Anyways pretty soon , I'll add whole content to my blog.

**Pull request closed without merging**
