### PR TITLE
Added fontawesome and social icons in menu

### PR DESCRIPTION
**Pull request by jfversluis**
To link our social media channels and a quick way do find the feed I have added the appropriate icons and added them to the menu. Fixing #57

### CODE REVIEW

**Comment by Cheesebaron** [comment]
Does this also work when the window is resized to phone size and it shows the hamburger icon?

**Comment by jfversluis** [comment]
Again; it needs some designer lovin' but it works

Normal:


Responsive:

**Comment by Cheesebaron** [comment]
Not sure if we could add text in the phone mode. Because the rows look very empty.

**Comment by jfversluis** [comment]
Added viewing of text now for mobile, not in LESS and I think I'll just stop these attempts until some serious redesign is done 😅

With text on mobile

**Pull request merged**
