### PR TITLE
Create DevlinDuldulao.cs

### PR DESCRIPTION
**Pull request by webmasterdevlin**
If you are submitting a new blog please read:

By sending this pull request to add my blog I verify that I adhere to the Planet Xamarin blog guidelines:

- I have a valid blog & RSS URL
- Host NO malicious or offensive content on the blog (including photos, swearing, etc.)
- Blog is active with at least 3 Xamarin related blog posts in the last 6 months
- If the blog has mixed content (Xamarin and Personal/Non-Xamarin blogs) a filter has been applied
- If you delete your blog you will come delete your blog from Planet Xamarin
- Your blog may be removed at any time if any of these are broken.

### CODE REVIEW

**Comment by webmasterdevlin** [comment]
@jfversluis , thanks for telling me this. I wasn't aware that it needs to be included in csproj..  Sorry.. 

I've Googled how to do it. But unfortunately, I've seen different things.

Can you please walk me through on doing it?

**Comment by webmasterdevlin** [comment]
Btw, with regards to my blog. I updated earlier its CMS core and its template to avoid any incompatibilities. You may check my blog anytime. Thank you.

**Comment by Cheesebaron** [comment]
Just look at the csproj file, and see how all the other authors are added. No need to google anything.

**Comment by webmasterdevlin** [comment]
@Cheesebaron , I just nailed it. =)

**Comment by webmasterdevlin** [comment]
@jfversluis Hope this would do it.

**Comment by Cheesebaron** [comment]
I've just read some of your blog posts. They appear really strange. Mixed English and Filipino. Some posts are 50% English and 50% Filipino, is this normal?

For instance:

> For several months, ang laking tulong ni Genymotion para mapabilis yung pag develop namin ng Android projects. Kailangan mo lang ng installer nya and installer ng Oracle Virtual Box.

Also your post about "Android Emulators" is full of misinformation.

The other two posts are not suited for aggregation as they just promote a Slack channel and promote your training services.

IMO, this should not be merged.

**Comment by webmasterdevlin** [comment]
@Cheesebaron and @jfversluis  thanks for your feedback. Yes, my blog is in Filipino-English language. This is normal conversation here in the Philippines which has pushed me to write Xamarin tips that can be easily understood by Filipinos.

I believe that there are terminologies that are better to be read or heard in a native language.

With regards to Android emulators, I used physical devices because it's a lot faster than vms, which I also shared on 1 of my posts.

I'm okay if my blog will not be included in Planet Xamarin's feed due the language I am using.

**Pull request closed without merging**
