### PR TITLE
Added Andrew Hoefling

### PR DESCRIPTION
**Pull request by ahoefling**
:pencil2: **Blog Url**: https://www.andrewhoefling.com

:scroll: **Feed Url**: 
* https://www.andrewhoefling.com/feed.xml
* https://www.andrewhoefling.com/feed.xml?category=xamarin

By sending this pull request to add my blog I verify that I adhere to the Planet Xamarin blog guidelines (please check each item that applies):

- [x] I have a valid blog & RSS URL, both using HTTPS :lock: with a valid certificate
- [x] I host NO malicious or offensive content on the blog (including photos, swearing, etc.)
- [x] My blog is active with at least 3 Xamarin related blog posts in the last 6 months
- [x] In addition to the previous guideline; it should be apperant that the blog is active for a longer period of time and the posts on it are not fabricated in a small amount of time to comply to the '3 posts in last 6 months' guideline.
- [x] I have applied a filter (Optional: if blog is only about Xamarin or you use `xamarin` in the title or categories in your blog posts)
- [x] I have added my Author class to the csproj file
- [x] I have implemented `IAmACommunityMember` or one of the other derivatives
- [x] I understand, if I delete my blog, I will be deleted from Planet Xamarin
- [x] I understand, my blog may be removed at any time if any of these guidelines are broken.
- [x] The submitted blog is not owned by a company which sole purpose it is to advertise a product of productline.

Only the collaborators of this repository decide whether a blog is eligible or not. They will determine if the rules are followed and if the quality of the content is high enough. 

Opening another PR, after the first one is closed in a small period of time will not be reevaluated. If a PR is closed, the issues with your blog are too significant to be fixed within a matter of hours.

### Notes
My blog is *not* only Xamarin. I configured the RSS feed to display only xamarin content though

### CODE REVIEW

**Comment by ahoefling** [comment]
Thanks for accepting me as a community blogger

@jfversluis How long should it take to start seeing my blog posts or my name listed as a community author? I released a new blog this morning (4am UTC) and didn't see it posted. As well I don't see my name listed as a community author.

Not sure how the build process works for deploying the changes.

**Comment by jfversluis** [comment]
That is strange, normally this happens automagically. @jamesmontemagno do you see anything while deploying? Build seem to be working just fine.

**Comment by DanielCauser** [comment]
I don't see @ahoefling as one of the Authors.

Screen Shot 2019-04-10 at 5 29 38 PM

**Comment by ahoefling** [comment]
@jamesmontemagno @jfversluis any updates on this?

**Comment by jfversluis** [comment]
I think James has been away for a trip and just got back. Hopefully, he will find some time to check this out

**Comment by jfversluis** [comment]
@ahoefling I think with another pr merged the deploy suddenly succeeded and your update was pushed as well :)

**Comment by ahoefling** [comment]
I confirmed it is working, thanks so much

**Pull request merged**
