### PR TITLE
Adding Allan Ritchie as Author

### PR DESCRIPTION
**Pull request by aritchie**
:pencil2: **Blog Url**: https://allancritchie.net

:scroll: **Feed Url**: https://allancritchie.net/xamarin.rss

By sending this pull request to add my blog I verify that I adhere to the Planet Xamarin blog guidelines (please check each item that applies):

- [x] I have a valid blog & RSS URL, both using HTTPS :lock: with a valid certificate
- [x] I host NO malicious or offensive content on the blog (including photos, swearing, etc.)
- [ ] My blog is active with at least 3 Xamarin related blog posts in the last 6 months
- [ ] In addition to the previous guideline; it should be apperant that the blog is active for a longer period of time and the posts on it are not fabricated in a small amount of time to comply to the '3 posts in last 6 months' guideline.
- [x] I have applied a filter (Optional: if blog is only about Xamarin or you use `xamarin` in the title or categories in your blog posts)
- [x] I have added my Author class to the csproj file
- [x] I have implemented `IAmACommunityMember` or one of the other derivatives
- [x] I understand, if I delete my blog, I will be deleted from Planet Xamarin
- [x] I understand, my blog may be removed at any time if any of these guidelines are broken.
- [x] The submitted blog is not owned by a company which sole purpose it is to advertise a product of productline.

Only the collaborators of this repository decide whether a blog is eligible or not. They will determine if the rules are followed and if the quality of the content is high enough. 

Opening another PR, after the first one is closed in a small period of time will not be reevaluated. If a PR is closed, the issues with your blog are too significant to be fixed within a matter of hours.

### CODE REVIEW

**Comment by DanielCauser** [comment]
Yaaaaas, I have been waiting a long time to see this guy here!

**Comment by nickrandolph** [comment]
@aritchie are you able to resolve the conflict and the failing build (it's probably because the unit tests aren't passing - check these by running them in VS)

**Comment by jfversluis** [comment]
@nickrandolph not so much something @aritchie can fix. Unit tests tend to fail most of the time because of other people's feeds being not reachable or empty. In this case, the one of Allan himself, simply because nothing is posted yet.

But in this case also the on of @icebeam7 since his cert expired yesterday, so Luis, please fix it ASAP or we will have to remove you :) 

Other than that, Alan contacted me directly to be able to get this PR merged and ensured me that, although he doesn't apply to the rules right now, he has enough content lined up and will make up for it. I choose to believe him seeing his track record.

**Comment by nickrandolph** [comment]
Ok, so we really should not be merging PRs that break the build - if we want to bypass a particular author we should add an exception to the tests so that it passes.
It's really bad form to have the tests failing - it means that any developer wanting to add their own details first has to work out why the unit tests are failing (thinking that they've broken something)

**Comment by jfversluis** [comment]
Normally I would agree, in this case, it is the only mechanism we have apart from manually checking all the feeds in here from time to time. So maybe the means (unit tests) isn't the best, in this case, giving false positives while nothing is broken in code, but it is all we have right now and has been working perfectly so far.

**Comment by nickrandolph** [comment]
@aritchie don't take this the wrong way as I know you're an active contributor to the Xamarin ecosystem.....
but by simply adding authors because they've posted once on something related to Xamarin devalues all the authors that continue to post on regular basis. If you're committed to blog about Xamarin then just submit the PR when you've got three posts.

@jfversluis are you suggesting that we change the guidelines for candidates for this feed (and thereby degrading the value of such a feed)? Or are we making a singular exception here because we understand the contribution that @aritchie makes?

**Comment by jfversluis** [comment]
Sorry if it wasn't clear, my decision on this was indeed meant as a singular exception because of Allan reaching out to me with this question. He ensured me that he has a number of posts lined up and just came out with a great new library I think we will all appreciate. My apologies if I didn't consult with the rest first, but for months Cheesebaron and I have been running this thing alone and we have kept the gate pretty tight, and now just once, just for Allan I will make an exception.

If you think this was in error or we should change things, maybe we should take it offline for a bit.

**Comment by nickrandolph** [comment]
yep, that's cool, just need to be clear on this as it is about the community. The rules are very clearly stated and as such the value of the content on the feed is great. 
I don't think we need to change the rules
I don't think we should ever merge PRs when the build is broken (there's so many alternatives to doing this!!!)
We should put a caveat on the rules that the maintainers have the final say and that they can electively override rules with providing suitable justification (which you have in this case)

**Comment by jfversluis** [comment]
> We should put a caveat on the rules that the maintainers have the final say and that they can electively override rules with providing suitable justification (which you have in this case)

It says something like that at the end of the PR, but apparently not clear enough.

I totally agree on the broken PR merges etc. up til now it has just been a mechanism that acts as a flag for manual checking, but I am very open to suggestions. I think when I said that Cheesebaron and I running things for the past time is also the "problem". This product has been out there for a while now, being stable and we know what to do and how we do it, but that includes a couple of not so great practices. So, it's good to have some fresh ideas, thanks for that!

**Comment by nickrandolph** [comment]
I'd suggest a couple of amendments to the unit tests to allow for a bit of a grace period:
- for new blogs (ie feed has <5 posts) they should be accepted so long as there is at least 1 xamarin post and that the feed is no older than say 3 months (being the time between now and the timestamp on the first post in the feed)
- for existing blogs if the blog is failing the 3 in 6 month criteria but still pass a lower threshold, say 3 in 12 months, they should be given another 3 months grace period.
These are just examples of how we could provide grace periods whilst still enforcing the checking with the unit tests

**Comment by aritchie** [comment]
@nickrandolph I just released a beta of a rather large Xamarin OSS framework I've been working on for a few months.  I wanted my blog to start rolling out the content immediately after getting on the planet xamarin twitter feed to generate some interest.  I literally have 18 articles all Xamarin related on the queue to roll out of the next couple of months.  Three of which will roll out over the next week.  I reached out to @jfversluis directly to see if he could help and he was totally supportive of it as he's mentioned.  

@jfversluis Thanks for the support.  It is truly appreciated.

**Pull request merged**
