### PR TITLE
Create VenkataramanaMadugula.cs file

### PR DESCRIPTION
**Pull request by VenkatsQuest**
I would like to add my blog posts related to Xamarin to get added to Planet Xamarin Community. Kindly approve this request.

If you are submitting a new blog please read:

By sending this pull request to add my blog I verify that I adhere to the Planet Xamarin blog guidelines (please check each item that applies):

- [x] I have a valid blog & RSS URL
- [x] I host NO malicious or offensive content on the blog (including photos, swearing, etc.)
- [x] My blog is active with at least 3 Xamarin related blog posts in the last 6 months
- [x] I have applied a filter (Optional: if blog is only about Xamarin)
- [x] I understand, if I delete my blog, I will be deleted from Planet Xamarin
- [x] I understand, my blog may be removed at any time if any of these guidelines are broken.

### CODE REVIEW

**Comment by VenkatsQuest** [comment]
@ghuntley Can you please approve #310 0b490c0  merge. Thanks.

**Comment by VenkatsQuest** [comment]
@jfversluis  i recommitted the changes. can you please review it and approve the same ? Thanks much.

**Comment by jfversluis** [comment]
The class is still not added to the csproj file, so it won't be compiled or included on the website.
And I will still have to check your site and content to see if it lives up to the standard we have set.

**Comment by VenkatsQuest** [comment]
@jfversluis #313( Added Authors\VenkataramanaMadugula.cs to the .csproj file) #314 ( Added the file to the correct location \Authors\VenkataramanaMadugula.cs ) file.
Kindly review my blog  ( www.madugulavenkataramana.com) and let me know if you've any questions.
Once again thanks for patience.

**Pull request closed without merging**
