### PR TITLE
Adding Amjad Al-husseini as a new author

### PR DESCRIPTION
**Pull request by amjad-Alhusseini**
If you are submitting a new blog please read:

By sending this pull request to add my blog I verify that I adhere to the Planet Xamarin blog guidelines:

- I have a valid blog & RSS URL
- Host NO malicious or offensive content on the blog (including photos, swearing, etc.)
- Blog is active with at least 3 Xamarin related blog posts in the last 6 months
- If the blog has mixed content (Xamarin and Personal/Non-Xamarin blogs) a filter has been applied
- If you delete your blog you will come delete your blog from Planet Xamarin
- Your blog may be removed at any time if any of these are broken.

### CODE REVIEW

**Comment by amjad-Alhusseini** [comment]
changes are done per requested

**Comment by Cheesebaron** [comment]
Build still fails:

```
Authors\AmjadHusseini.cs(7,34): error CS0535: 'AmjadHusseini' does not implement interface member 'IAmACommunityMember.GitHubHandle' [C:\projects\planetxamarin\src\Firehose.Web\Firehose.Web.csproj]
Authors\AmjadHusseini.cs(7,34): error CS0535: 'AmjadHusseini' does not implement interface member 'IAmACommunityMember.Position' [C:\projects\planetxamarin\src\Firehose.Web\Firehose.Web.csproj]
```

**Comment by amjad-Alhusseini** [comment]
Errors are fixed, apologies for any inconvenience.

**Comment by amjad-Alhusseini** [comment]
Is there any errors left?

**Comment by jfversluis** [comment]
Hi Amjad,

Thank you for reaching out to me by e-mail and your interest in being a Planet Xamarin author. First off; I'm sorry it took so long for someone to respond.

I have inspected the code you have submitted and vetted your feed and posts. While technically you seem to meet all the requirements, I will not add your feed just yet. One of the rules we have drawn up is: 'Blog is active with at least 3 Xamarin related blog posts in the last 6 months'.
The last post is from April and before that February, so it is about to fall out of the criteria we've et very soon. Also, the posts seem to cover very basic topics.

I hope you don't get this the wrong way. I'm not trying to criticize you, it's just that we are looking for some specifics in the content. I hope this will encourage you to create more, in-depth posts and then you will be added in no time!

Cheers!

**Comment by amjad-Alhusseini** [comment]
Hi,

Thank you for reaching back to me.

Yes, at the moment i have 6 blog posts all related to Xamarin but as you said lately i haven't been that active but the time i submitted my pull request it was more active than now.

Anyway, shall i contact you whenever i have something new? Or what do you suggest?

Regards
Amjad

Regards,
Amjad
________________________________

**Comment by amjad-Alhusseini** [comment]
Oh no, actually my last post was in 30th of june!

And this is the link for it http://amjadhusseini.com/2017/06/30/consuming-authenticated-apis-with-xamarin-forms/

And actually it's a massive one, it took alot of time from me to finish it.

Does that count me as active lately?

Regards,
Amjad
_____________________________

**Comment by jfversluis** [comment]
Hi Amjad,

You're right! And of course that does count as active. I'd like to see more content like that ones. Although it seems to contain a lot of code inline. Try to cut that back a little and a bit more explaining text. Create more posts like this last one and submit another PR so we can take look at the content then.

Thanks!

**Pull request closed without merging**
