### PR TITLE
Requesting to be added

### PR DESCRIPTION
**Pull request by deanilvincent**
If you are submitting a new blog please read:

By sending this pull request to add my blog I verify that I adhere to the Planet Xamarin blog guidelines (please check each item that applies):

- [x] I have a valid blog & RSS URL
- [x] I host NO malicious or offensive content on the blog (including photos, swearing, etc.)
- [x] My blog is active with at least 3 Xamarin related blog posts in the last 6 months
- [x] I have applied a filter (Optional: if blog is only about Xamarin)
- [x] I understand, if I delete my blog, I will be deleted from Planet Xamarin
- [x] I understand, my blog may be removed at any time if any of these guidelines are broken.

### CODE REVIEW

**Comment by jfversluis** [comment]
Thank you for your PR! Great to see you got it working!

A few things:
- You did not update the .csproj file, so your file will not be compiled and thus not be included in the website
- Your feed URL seems to give a 404?

**Comment by Cheesebaron** [comment]
For the feed url it seems like removing the trailing slash helps.

**Comment by deanilvincent** [comment]
@jfversluis Oh I see, yeah it's because of the / at the end of my feed. I'm sorry for that. :) Thank you @Cheesebaron and @jfversluis

**Comment by jfversluis** [comment]
Hi Deanil, thank you for wanting to be part of Planet Xamarin!

I have just looked at your blog, and I will not add it just yet.

I really do like your posts. There are clear and full of screenshots. And maybe that is the problem, it is a bit too easy to follow along.
For the most part you are telling people where to click. What I am missing is some more explaining. Like why are you doing certain things? Where can people expect problems? Are there any other ways to do this? And why did you choose this one?

You see what I mean? Your posts now result in a working app, but afterwards they have no idea what they did and why they did it. I'd like to see some more opportunity to learn in here.

Please work on that in your coming posts and we'll gladly see another PR coming in a couple of months.

**Comment by deanilvincent** [comment]
Hello @jfversluis Thank you for your suggestions. I'll consider your tips in creating new post next time. I hope next coming press release, I'll be considered as one of the authors. :)

**Comment by jfversluis** [comment]
Great! I look forward to your posts. Not to be rude, but to make sure we’re on the same page: I’d like to see more than one post. So, creating another pr right after your next post would be too soon imho.

Good luck and thank you!

**Pull request closed without merging**
