### PR TITLE
Enable TLS 1.3

### PR DESCRIPTION
**Pull request by kjacobsen**
Enable support for TLS 1.3 (for hosts that do not support TLS 1.2 or TLS 1.1)

### CODE REVIEW

**Comment by kjacobsen** [comment]
Might require framework version bump. Planet PowerShell is now on 4.8 hence this works.

**Comment by kjacobsen** [comment]
Changing the targeted version is a bit of a long thread to pull.

**Comment by jamesmontemagno** [comment]
Anything special you needed to do for 4.8/TLS 1.3?

I would love to move these projects to .NET 6 that is for sure.

**Comment by jamesmontemagno** [comment]
I didnt' even realize the PS community had a site that is awesome! was able to use that repo as a reference :) now running 4.8!

**Pull request merged**
