### PR TITLE
Create UmairHassan.cs

### PR DESCRIPTION
**Pull request by umair03**
:pencil2: **Blog Url**: https://xamarinweb.com

:scroll: **Feed Url**: https://xamarinweb.com/blog/feed/

By sending this pull request to add my blog I verify that I adhere to the Planet Xamarin blog guidelines (please check each item that applies):

- [x] I have a valid blog & RSS URL, both using HTTPS :lock: with a valid certificate
- [x] I host NO malicious or offensive content on the blog (including photos, swearing, etc.)
- [x] My blog is active with at least 3 Xamarin related blog posts in the last 6 months
- [x] In addition to the previous guideline; it should be apperant that the blog is active for a longer period of time and the posts on it are not fabricated in a small amount of time to comply to the '3 posts in last 6 months' guideline.
- [x] I have applied a filter (Optional: if blog is only about Xamarin or you use `xamarin` in the title or categories in your blog posts)
- [x] I have added my Author class to the csproj file
- [x] I have implemented `IAmACommunityMember` or one of the other derivatives
- [x] I understand, if I delete my blog, I will be deleted from Planet Xamarin
- [x] I understand, my blog may be removed at any time if any of these guidelines are broken.
- [x] The submitted blog is not owned by a company which sole purpose it is to advertise a product of productline.

Only the collaborators of this repository decide whether a blog is eligible or not. They will determine if the rules are followed and if the quality of the content is high enough. 

Opening another PR, after the first one is closed in a small period of time will not be reevaluated. If a PR is closed, the issues with your blog are too significant to be fixed within a matter of hours.

### CODE REVIEW

**Comment by jfversluis** [comment]
If you don’t add yourself to the csproj your blog will never be included.

**Comment by jfversluis** [comment]
Also, https is a requirement. You did check it off the list, but your urls are http

**Comment by umair03** [comment]
@jfversluis  added <Compile Include="Authors\UmairHassan.cs" /> in .csproj file

**Comment by jfversluis** [comment]
I closed #491. Please do all changes in one PR

**Comment by Cheesebaron** [comment]
You don't have a valid SSL certificate.

**Comment by umair03** [comment]
@Cheesebaron  SSL Certificate is now Updated

**Comment by jfversluis** [comment]
Your ssl certificate still isn’t valid

**Comment by Cheesebaron** [comment]
Your SSL certificate is a self signed certificate. You need a trusted issue to create it for you. This could be LetsEncrypt, CloudFlare or a certificate you buy.

**Comment by umair03** [comment]
@Cheesebaron  @jfversluis  CloudFlare Certificate is now successfully activated on my site. Is everything ok now?

**Comment by Cheesebaron** [comment]
Much better. Please add your urls to the top of the opening post.

**Comment by umair03** [comment]
@Cheesebaron  Added

**Comment by umair03** [comment]
@Cheesebaron  @jfversluis  Did you know. who can review and merge this pull request?

**Comment by umair03** [comment]
Waiting for request to be reviewed and merged.

**Comment by Cheesebaron** [comment]
It would help a lot if you wrote some articles, which had some more meat.

Also you should attribute images you use accordingly. Several of the images you use that are on the front page are not your intellectual property and you haven't stated the source.

Also your articles have severe code formatting issues.

Please address these.

**Pull request closed without merging**
