### PR TITLE
Added new author from Peru

### PR DESCRIPTION
**Pull request by wilsonvargas**
Added new author from Peru

### CODE REVIEW

**Comment by jfversluis** [comment]
I see no HTTPS as per #334 and stopped looking there.

Please add HTTPS first before we're considering you to be added.

**Comment by Cheesebaron** [comment]
Also please use the PR template and mark all the checkboxes.

**Comment by jfversluis** [comment]
A week without response, closing this one.

**Comment by wilsonvargas** [comment]
please reopen  my pull request 😄

**Comment by wilsonvargas** [comment]
cc @jfversluis,  @Cheesebaron

**Pull request closed without merging**
