### PR TITLE
add CarelLotz as author

### PR DESCRIPTION
**Pull request by cjlotz**
If you are submitting a new blog please read:

By sending this pull request to add my blog I verify that I adhere to the Planet Xamarin blog guidelines:

- I have a valid blog & RSS URL
- Host NO malicious or offensive content on the blog (including photos, swearing, etc.)
- Blog is active with at least 3 Xamarin related blog posts in the last 6 months
- If the blog has mixed content (Xamarin and Personal/Non-Xamarin blogs) a filter has been applied
- If you delete your blog you will come delete your blog from Planet Xamarin
- Your blog may be removed at any time if any of these are broken.

### CODE REVIEW

**Comment by cjlotz** [comment]
Anything missing here?

**Comment by jfversluis** [comment]
Don't get this the wrong way; but 90% of your blog posts are release notes on your plugins. While this is very useful and I am very grateful for those plugins, it doesn't actually add any 'real' content. I'd like to see more blog posts like your last one. Inspired on actual problems in your every day job.

But that is jut my opinion. @Cheesebaron what do you think?

**Comment by jamesmontemagno** [comment]
I think maybe add a filter :)

**Comment by cjlotz** [comment]
I don't mind guys.  This is really no big issue to me.  I'll add more content over time and I'll revisit this pull request later on to see whether you guys feel I'm adding enough value in the Xamarin community :-)

**Comment by jamesmontemagno** [comment]
@cjlotz I think you totally do. I think basically I would see if you can add tags to your posts about releases and just don't include them. On my blog i only have stuff that I mark Xamarin for instance.

**Pull request merged**
